name: bluback.com
layout_spectrum: 0.25444
typography_spectrum: 0.74685
cta: {}
analytics: {}
opengraph: {}
color:
  brandColors:
    - '#624541'
    - '#3b2720'
    - '#e7c7b2'
    - '#b38466'
    - '#bab484'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
title: 'Get blu back '
