name: bluback.com
favicon: null
layout_spectrum: 0.25444
typography_spectrum: 0.74685
title: 'Get blu back '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#624541'
    - '#3b2720'
    - '#e7c7b2'
    - '#b38466'
    - '#bab484'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
