name: bluback.com
favicon: null
layout_spectrum: 0.25444
typography_spectrum: 0.74685
title: 'Get blu back '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#ae8875'
    - '#5a413a'
    - '#2c180d'
    - '#2cb1e9'
  brandStrength: 0.4375
  lightness: 0.43223767285235226
  saturation: 0.45770307001657784
  rhythmicContrast: 0.49746500281617045
purpose: []
